version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 3000:80
    networks:
      - my-network
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    volumes: 
      - db-data:/var/lib/mysql
    networks:
      - my-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
        
volumes:
  db-data: {}

networks:
  my-network:

